### ISSUE TITLE
[BUG] ACM Black is #181818

### ISSUE THREAD

**Issue by tfukaza** [uclaacm/Styleguide#60]
**Describe the bug**
![image](https://user-images.githubusercontent.com/40327230/99140907-9c580d00-25fa-11eb-91f0-6066ed7297fe.png)
This should be #181818

**Comment by andygoh5** [comment]
I put the wrong RGB value...put 18s for everything. It should be (24, 24, 24)
![Screen Shot 2020-11-24 at 10 24 46 AM](https://user-images.githubusercontent.com/37412267/100135995-47f52e80-2e3f-11eb-9557-f2f0e4b47312.png)

**Comment by andygoh5** [comment]
Fixed with this commit: https://github.com/uclaacm/Styleguide/commit/1623ea1c107fd1f8e59234c5fb00fa5ed4812037
